# Generated by Django 1.11.10 on 2018-03-09 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_processinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinfo',
            name='pid',
            field=models.SmallIntegerField(db_index=True, help_text='process ID.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sitestatistics',
            name='site',
            field=models.OneToOneField(default=settings.SITE_ID, help_text='settings.SITE_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.Site'),
        ),
    ]
