# Generated by Django 3.1.2 on 2020-11-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_processinfo', '0002_auto_20180309_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinfo',
            name='alive',
            field=models.BooleanField(help_text="Is this process dead (==False)? *Important:* alive is never==True! If alive==None: State unknown! (We don't check the state in every request!)", null=True),
        ),
    ]
