# Generated by Django 3.1.2 on 2020-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_processinfo', '0003_auto_20201102_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinfo',
            name='pid',
            field=models.PositiveIntegerField(db_index=True, help_text='process ID.', primary_key=True, serialize=False),
        ),
    ]
